- tnt/v2/tnt.yaml
As reported in #12, transportCallID should not be part of the Event object, as the Shipment Event subtype does not have the property
> Remove transportCallID in shipmentEvent

- ebl/v1/ebl.yaml
add v1 in beginning of path to reflect API Design guide
reordered paths
changed PUT response to 202 accepted instead of 200 OK to align with POST
Removed X as prefix for header name in order to align with API Design guide
> API definition transferred by SwaggerHub

- ovs/v2/ovs.yaml
Update API description
Add /v2/... to all endPoints
Created the GET /v2/events to be aligned with all other APIs
Add carrierServiceCode query parameter to GET /v2/events endPoint
Add eventCreatedDateTime query parameter to GET /v2/events endPoint
Remove POST /transport-calls as this is not part of the official API
Add POST /v2/timestamps to create timestamps for negotiation between vessel and port
Remove PUT /transprot-calls as this is not part of the official API
Add optional API-Version header to all requests
> Latest updates from SwaggerSpec

- bkg/v2/BKG_v2.0.0-Beta-2.yaml
- ebl/v3/EBL_v3.0.0-Beta-2.yaml
DT-823: Split the `field` property into 2 properties: `property` and `jsonPath`. They are both optional so can be provided if needed (in the PR example - Booking uses both properties and in EBL only the `jsonPath` property is used)
> DT-823: Align requestedChange with ErrorResponse object

- bkg/v2/notification/BKG_NTF_v2.0.0-Beta-2.yaml
- ebl/v3/notification/EBL_NTF_v3.0.0-Beta-2.yaml
Add `subscriptionReference` to CloudEvent root level.
Update examples
Add missing API license text (copied from Booking license)
> DT-1007: Add subscriptionReference to Notification APIs

- ebl/v3/surrender/EBL_SUR_v3.0.0-Beta-2.yaml
Expanding all $ref
DT-992 is included in this PR (update Stats API)
Update Party-objects to be more in line with Booking and EBL
Modified the eblPlatform from 40 characters --> 4 characters
Removed the allOf construction for the `surrenderRequestedBy` and made a separate object (this will be validated by Spectral)
Covers DT-930 and DT-983 and DT-984
eblPlatform list updated
identifyingCode structure updated
> DT-1004: Move Surrender API from SwaggerHub --> StopLight

- bkg/v2/BKG_v2.0.0-Beta-3.yaml
Added `title` properties to all objects defined
Removed `title` property on the `reason` simpleType (it is not an object)
Improved a few descriptions that stoplight had "automodified" near places I anyhow modified
> DT-1189: Add missing title property (and remove title from reason)

- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
Only add it as part of the description as the `volume` property is optional and `volumeUnit` is only mandatory **IF** `volume` is provided
> DT-1152: Add volumeUnit being conditional on volume

- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
Since the `displayedNameFor...` properties are optional - then minItems=1 should be removed as it is allowed not to provide any items...
> DT-1165: Remove minItems on optional arrays

- an/v1/AN_v1.0.0-Beta-1.yaml
- bkg/v2/BKG_v2.0.0-Beta-3.yaml
- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
Imperial units are missing on the `netExplosiveContent` peroperty in DG (DangerousGoods). Adding here for consistency as we have imperial units on **all** other units
> DT-1187: Add imperial units to netExplosiveContent

- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
A new boolean `isCarriersAgentAtDestinationRequired` is added to the root of CreateShippingInstructions, UpdateShippingInstructions and ShippingInstructions
A new documentParty `carriersAgentAtDestination` is added to the `TransportDocument` which links to a `CarriersAgentAtDestination` object
Removed UNLocationCode from `CarriersAgentAtDestination` address since it is not needed
> DT-1208: Add Carrier's Agent at Destination to documentParties

- bkg/v2/BKG_v2.0.0-Beta-3.yaml
- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- ebl/v3/surrender/EBL_SUR_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
[DT-1193](https://dcsa.atlassian.net/browse/DT-1193): Remove quotes around pattern values as StopLight has invalidated many of them
[DT-1193]: https://dcsa.atlassian.net/browse/DT-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1193: Remove quotes around pattern values

- bkg/v2/BKG_v2.0.0-Beta-3.yaml
There are still some items left in the error tab:
* all errors related to `oneOf`, `anyOf` or `allOf` as this needs to be fixed in Spectral (not supported yet) - this shows up as a problem for UNLocationCode and countryCode
* The required fields on Address and PartyAddress have been fixed in the Spectral rules (in another PR)
* postCode maxLength has been changed to 10 in another PR
* all objects with discriminators need to be fixed in Spectral (not supported yet)
* unit enum needs to be fixed in Spectral (not supported yet - will be fixed in another PR)
* $ref link on ActiveReeferSettings needs to be fixed in Spectral (not supported yet - will be fixed in another PR)
This PR fixed the following Spectral errors:
* catastrophic backtracking on importLicenseRefernce
* wrong order of …
> DT-1188: Fix some of the BKG Spectral errors

- ebl/v3/EBL_v3.0.0-Beta-3.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
Fixes:
* update Booking version: Beta 2 --> Beta 3
* missing titles from objects
* missing patterns added
* missing string examples
* title removed from `reason` field
* renamed `vesselVoyage` --> `vesselVoyages` and changed inline object to being a root level object
* add missing `type: object` where needed
* add missing `maxLength: 4` on `locationType`
> DT-1229: Fix issues found by Spectral to make EBL+ISS+SUR APIs consistent

- ovs/v3/OVS_v3.0.1.yaml
Changed errorDateTime example to UTC for OVS_3.0.1
> Fixed errorDatetime example

- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
Remove ECR (Empty Container Release) and BID (Booking Request ID) from the EBL references [DT-1257](https://dcsa.atlassian.net/browse/DT-1257)
[DT-1257]: https://dcsa.atlassian.net/browse/DT-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1257: Remove ECR and BID from EBL ReferenceType

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
Update according to [DT-1316](https://dcsa.atlassian.net/browse/DT-1316):
1. Applicable to BKG & BL 
a). Remove reference types SAC, BID, CSI. During DCSA week multiple carriers argued that some reference types should be removed since there is no use for them in the standards. After further discussion and clarifications in the DT SME meeting of July 1, 2024, the majority has agreed to remove the mentioned ones.
b). Add AKG (Vehicle Identification Number) on the equipment and commodity level, defined as: A unique code used by the automotive industry to identify individual motor vehicles, towed vehicles, motorcycles, scooters and mopeds as defined in ISO 3779 and ISO 4030. 
2. Applicable to BKG
a). Add AEF (Customer Load Reference) on the equipment level defined as: Retrieval number for a …
> DT-1316: Update references

- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- ebl/v3/issuance_response/EBL_ISS_RSP_v3.0.0-Beta-3.yaml
- ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
- ebl/v3/surrender_response/EBL_SUR_RSP_v3.0.0-Beta-3.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
- reference-data/eblsolutionproviders-v3.0.0.csv
This PR replaces #279 (commit 1)
It also:
* merges the ISS_RSP API into the ISS API + deprecate ISS_RSP API (commit 2)
* merges the SUR_RSP into the SUR API + deprecate SUR_RSP API (commit 3)
Note: Spectral file has not been updated as it is currently being updated as part of another PR and cannot be modified in multiple PRs :-( Will update it later
This links to Jira issue [DT-1438](https://dcsa.atlassian.net/browse/DT-1438)
[DT-1438]: https://dcsa.atlassian.net/browse/DT-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update APIs according to #279

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
The description in the API was out-of-date with the description in the IFS.
**Note:** The `TransportDocument` has a condition which is added to all descriptions (except the one in Booking)
Links to: [DT-1495](https://dcsa.atlassian.net/browse/DT-1495)
[DT-1495]: https://dcsa.atlassian.net/browse/DT-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1495: Update declaredValue description and add extra condition for TD

- bkg/v2/BKG_v2.0.0.yaml
Fix bug in Address object examples - `name` property is no longer part of the Address object
> Remove name in Address examples

- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1590](https://dcsa.atlassian.net/browse/DT-1590) - Receiver in the PINT API was forgotten in the original PR - fixed here
[DT-1590]: https://dcsa.atlassian.net/browse/DT-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1590,DT-1512: Modify partyName maxLength on Receiver

- cs/v1/CS_v1.0.0.yaml
This PR includes the below jira issues : 
- [APCV-1217](https://dcsa.atlassian.net/browse/APCV-1217) - Added pagination link headers to all the endpoints
- [APCV-1218](https://dcsa.atlassian.net/browse/APCV-1218) - Removed Stats API link and text 
- [APCV- 1219](https://dcsa.atlassian.net/browse/APCV-1219) - Updated the limit parameter description and the description regarding filters in vesselSchedules endpoint.
- [APCV-1228](https://dcsa.atlassian.net/browse/APCV-1228) - Updated the description of transitTime and cutOffTimes
- [APCV-1230](https://dcsa.atlassian.net/browse/APCV-1230) - Updated the API design principles link in API spec
[APCV-1217]: https://dcsa.atlassian.net/browse/APCV-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> CS API- Pagination and description of various attribute changes

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1529](https://dcsa.atlassian.net/browse/DT-1529),[DT-1531](https://dcsa.atlassian.net/browse/DT-1531),[DT-1532](https://dcsa.atlassian.net/browse/DT-1532) - Data validations in Booking and EBL. In general this invloces:
- removing links to GitHub reference data
- removing links to specific versions of externally maintained reference data (and only link to the general page)
- where possible link to ISO instead of Wikipedia
As a side effect - updated some examples.
[DT-1529]: https://dcsa.atlassian.net/browse/DT-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1531]: https://dcsa.atlassian.net/browse/DT-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1532]: …
> Dt-1529,DT-1531,DT-1532: Remove GitHub links and remove links to specific versions

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1671](https://dcsa.atlassian.net/browse/DT-1671) - Update City property descriptions to not include "Party" since they are used for locations
[DT-1671]: https://dcsa.atlassian.net/browse/DT-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1671,DT-1674: Remove "Party" from location address descriptions

- cs/v1/CS_v1.0.0.yaml
Updated the DCSA error codes link to  https://developer.dcsa.org/standard-error-codes
> APCV-1341-Update DCSA error codes link

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1720](https://dcsa.atlassian.net/browse/DT-1720),[DT-1725](https://dcsa.atlassian.net/browse/DT-1725),[DT-1655](https://dcsa.atlassian.net/browse/DT-1655): Update description on properties that are arrays in which the order needs to be preserved. This specially goes for lists of lines in an Address or any other properties that contain a description in the form of lines
Some minor alignments on how to write `**Condition:**` is also stream lined
[DT-1720]: https://dcsa.atlassian.net/browse/DT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1725]: https://dcsa.atlassian.net/browse/DT-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1655]: …
> DT-1720,DT-1725,DT-1655: Update description on arrays that need to preserve order

- ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
[DT-1823](https://dcsa.atlassian.net/browse/DT-1823): Remove `surrenderRequestedBy` as a required proeprty as it is not part of the object it is mentioned in
[DT-1823]: https://dcsa.atlassian.net/browse/DT-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1823: Remove required property `surrenderRequestedBy`

- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1836](https://dcsa.atlassian.net/browse/DT-1836),[DT-1838](https://dcsa.atlassian.net/browse/DT-1838): Remove the condition on `carrierBookingReference` as it is currently "Out of Scope" for DCSA to define the requirements for combined bookings
[DT-1836]: https://dcsa.atlassian.net/browse/DT-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1838]: https://dcsa.atlassian.net/browse/DT-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1836: Remove conditions linking to multiple bookings from TD

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[DT-1858](https://dcsa.atlassian.net/browse/DT-1858): Add a condition to `declaredValueCurrency` to make it mandatory if `declaredValue` is provided
[DT-1858]: https://dcsa.atlassian.net/browse/DT-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DT-1858: Add a condition to `declaredValueCurrency`

- ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
[SD-652](https://dcsa.atlassian.net/browse/SD-652): Update the Surrender API description to indicate that a B/L must be surrendered from the same Solution Platform (SP) as it was Issued to.
@palatsangeetha lets merge this. If the PO comes back and wants to modify the description - then a new issue should be made
[SD-652]: https://dcsa.atlassian.net/browse/SD-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-652: Update the Surrender API description

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[SD-633](https://dcsa.atlassian.net/browse/SD-633),[SD-1489](https://dcsa.atlassian.net/browse/SD-1489): Make sure it is clear that only one of the two options is allowed (when applicable) - hence changing the wording "either" to "one of" to make it more clear.
Side fix: aligning how `unit` is described across the APIs
Adding extra conditions as requested by PO
[SD-633]: https://dcsa.atlassian.net/browse/SD-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SD-1489]: https://dcsa.atlassian.net/browse/SD-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-633: Change the wording "either" to "one of" to be more precise

- ebl/v3/EBL_v3.0.0.yaml
[SD-1507](https://dcsa.atlassian.net/browse/SD-1507): Update PUT /SI description to make it clear that the status of `updatedShippingInstructionStatus` does not matter
[SD-1507]: https://dcsa.atlassian.net/browse/SD-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1507: Update the PUT description of SI

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[SD-1759](https://dcsa.atlassian.net/browse/SD-1759): Fix copy/paste error in O^2 description
[SD-1759]: https://dcsa.atlassian.net/browse/SD-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1759: Fix wrong O^2 description

- bkg/v2/BKG_v2.0.0.yaml
- ebl/v3/EBL_v3.0.0.yaml
[SD-1701](https://dcsa.atlassian.net/browse/SD-1701): It is **not** possible in SwaggerHub to avoid endPoints with empty payloads to not be renendered. To make it more explicit this PR makes sure to add the `null` next to the value property in the example.
[SD-1701]: https://dcsa.atlassian.net/browse/SD-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1701: Add `null` to value-property in endPoints with empty responses

- ebl/v3/EBL_v3.0.0.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
- ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[SD-1736](https://dcsa.atlassian.net/browse/SD-1736): Align how eBL is referred to (don't use **E**BL)
Side fix: `DCSA_EBL_ISS_RSP API` was wrongly referred to --> change it to the `/v3/ebl-issuance-responses` endPoint
[SD-1736]: https://dcsa.atlassian.net/browse/SD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1736: Convert `EBL` to `eBL`

- ebl/v3/EBL_v3.0.0.yaml
[SD-1779](https://dcsa.atlassian.net/browse/SD-1779): Remove wrong condition for `identifyingCodes` on `Consignee` and `Endorsee` (as both properties are required)
[SD-1779]: https://dcsa.atlassian.net/browse/SD-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1779: Remove condition on IdentifyingCodes as it is mandatory

- pint/v3/EBL_PINT_v3.0.0.yaml
Enhancement
___
- Added a new `controlTrackingRegistry` field to the schema.
- Defined the purpose and conditions for the `controlTrackingRegistry` field.
- Enhanced PINT transfer protection with Control Tracking Registry (CTR) integration.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>EBL_PINT_v3.0.0.yaml</strong><dd><code>Added `controlTrackingRegistry` field for CTR integration</code></dd></summary>
<hr>
pint/v3/EBL_PINT_v3.0.0.yaml
<li>Introduced a new <code>controlTrackingRegistry</code> field in the schema.<br> <li> Added detailed description and conditions for the field.<br> <li> Enhanced schema to support CTR-based PINT transfer protection.
</details> …
> CTR-270: Add CTR URL in the PINT transfer

- jit/v2/JIT_v2.0.0.yaml
[SD-1917](https://dcsa.atlassian.net/browse/SD-1917): Adding `Next-Page-Cursor` header to all Collection results (all GET endPoints)
[SD-1917]: https://dcsa.atlassian.net/browse/SD-1917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1917: Make sure Next-Page-Cursor header is included in Collection results

- jit/v2/JIT_v2.0.0.yaml
[SD-1818](https://dcsa.atlassian.net/browse/SD-1818): Update descriptions for all endPoints
In addition updated:
* removed `Next-Page-Cusor` headers
* removed `limit` and `cursor` queryParameters
* added a lot of endPoint examples
* added `409` (Conflict) response code
* updated the filter parameters for (almost) all endPoints
* Remove conflicting ISO 8601 reference
@jkosternl adding you FYI (feel free to comment if you find anything :-) )
[SD-1818]: https://dcsa.atlassian.net/browse/SD-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1818: Update endPoints descriptions

- jit/v2/JIT_v2.0.0.yaml
[SD-1989](https://dcsa.atlassian.net/browse/SD-1989): Fix `classifierCode` queryParameter bug
[SD-1989]: https://dcsa.atlassian.net/browse/SD-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1989: Fix classifierCode query parameter bug

- jit/v2/JIT_v2.0.0.yaml
[SD-1824](https://dcsa.atlassian.net/browse/SD-1824): Removing 'v2/' from all URLs/examples and descriptions.
FYI: @jkosternl and @gj0dcsa 
[SD-1824]: https://dcsa.atlassian.net/browse/SD-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-1824: Remove 'v2/' from the urls

- jit/v2/JIT_v2.0.0.yaml
[SD-2050](https://dcsa.atlassian.net/browse/SD-2050) (included in Commit 1):
* Added some markdown so `Port Call`, `Port Call Service`, `Terminal Call` and `Timestamp` all are formatted in **bold** (and capitalized).
* Also improved the response description of the POST /port-calls endPoint
[SD-2036](https://dcsa.atlassian.net/browse/SD-2036) (included in Commit 2):
* Add `optional` to optional-properties in descriptions that already inline mention some properties as mandatory
[SD-2056](https://dcsa.atlassian.net/browse/SD-2056) (included in Commit 3):
* Remove the text that requires the value of a filter queryParameter to be part of the result payload
This PR does not modify formatting in summary-, example- or title-properties
[SD-2050]: …
> SD-2050, SD-2036, SD-2056: JIT 2.0: Modify descriptions

- jit/v2/JIT_v2.0.0.yaml
Make sure the spec follows the API DNI principles:
> A custom header called API-Version MUST be added in the response to specify the full version. The API-Version custom header in the response MUST include complete version information for example: API-Version: 2.0.0-beta-3. An API Consumer MAY use this information to adapt processing of the response in order to make use of features introduced into later versions of the standard.
> SD-2046: JIT 2.0: Make API-Version header required

- jit/v2/JIT_v2.0.0.yaml
[SD-2048](https://dcsa.atlassian.net/browse/SD-2048):
* Make sure not to report `404` (Not Found) error when a "reference" property in a payload does not exist. Moved the example to the `400` (Bad Request) instead
* Made sure UUID examples are not reused between `portCallID` and `terminalCallID`. Also made some other UUIDs "more" unique
[SD-2048]: https://dcsa.atlassian.net/browse/SD-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-2048: JIT 2.0: Update error response code descriptions

- jit/v2/JIT_v2.0.0.yaml
[SD-2062](https://dcsa.atlassian.net/browse/SD-2062): Adding a `Sending-Party` and `Receiving-Party` to all requests in JIT
Fixed missing `API-Version` header on the **port-call-Service** cancel endPoint
[SD-2062]: https://dcsa.atlassian.net/browse/SD-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-2062: JIT 2.0: Add `sender` and `receiver` headers

- jit/v2/JIT_v2.0.0.yaml
[SD-2062](https://dcsa.atlassian.net/browse/SD-2062): Make JIT "Hubbable":
- Rename the two headers `Sending-Party` and `Receiving-Party` to `Request-Sending-Party` and `Request-Receiving-Party`
- Add 2 extra response headers: `Response-Sending-Party` and `Response-Receiving-Party` to all endPoint responses
[SD-2062]: https://dcsa.atlassian.net/browse/SD-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SD-2062: JIT 2.0: Update headers to make JIT Hubbable

- bkg/v2/BKG_v2.0.3.yaml
- ebl/v3/EBL_v3.0.2.yaml
- ebl/v3/issuance/EBL_ISS_v3.0.2.yaml
- ebl/v3/surrender/EBL_SUR_v3.0.2.yaml
- pint/v3/EBL_PINT_v3.0.0.yaml
[SD-2232](https://dcsa.atlassian.net/browse/SD-2232): Make sure to include `ZZ` as `countryCode` in eBL, Issuance, Surrender (if needed) and PINT
[SD-2232]: https://dcsa.atlassian.net/browse/SD-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EBL 3.0: SD-2232: Add 'ZZ' option to countryCode

- ovs/v3/OVS_v3.0.1.yaml
[SD-42](https://dcsa.atlassian.net/browse/SD-42): Add `vesselOperatorSMDGLinerCode` as filter
___
Enhancement
___
- Add `vesselOperatorSMDGLinerCode` query parameter filter
- Enable filtering by SMDG liner code for vessel operators
___
```mermaid
flowchart LR
API["OVS API"] --> Filter["vesselOperatorSMDGLinerCode Filter"] --> Results["Filtered Schedule Results"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>OVS_v3.0.1.yaml</strong><dd><code>Add vessel operator SMDG liner code filter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> OVS 3.0: SD-42: Add vesselOperatorSMDGLinerCode filter
