v1/swagger.yaml

Release 1.1

---

ebl/v1/ebl.yaml

Simplify and only keep endPoint definitions
Refer to DCSA_EBL_DOMAIN for object references
Refer to DCSA_DOMAIN for Simple type references

Swaggerhub ebl v1

---

tnt/v3/tnt.yaml

All event* changed to notification*
endPoint names changed from event* -> notification*
Project uses DCSA_NOTIFICATION_DOMAIN and DCSA_DOMAIN

API definition transferred by SwaggerHub

---

domain/dcsa_ebl_domain.yaml

Remove IDs from objects where not needed
Clean up

Remove IDs

---

domain/dcsa_domain.yaml

Remove some unused fields
OVS updates

Minor changes

---

documentation_event_hub/v1/documentation_event_hub.yaml
domain/event_domain.yaml
event_hub/v1/event_hub.yaml
ovs_event_hub/v1/ovs_event_hub.yaml

Create all event hubs:
* Event Hub (event hub for all event types)
* Documentation Event Hub (for Shipment events)
* OVS Event Hub (event Hub for Transport and Operations events)

Add all event hubs

---

ebl/v1/ebl.yaml

EBL_DOMAIN changed to DOCUMENTATION_DOMAIN
GET /events queryParameters updated

Swaggerhub dcsa ebl 1.0.0

---

ovs_event_hub/v1/ovs_event_hub.yaml

Add pagination headers
Add API-Version header
rename internal names
Remove linkage to EVENT_HUB
Remove QueryParam and PathParam from all internal names

Push from SwaggerHub.

---

event_hub/v1/event_hub.yaml

Swaggerhub event hub 1.0.0

---

tnt/v2/tnt.yaml

Update from 2.0.1 -> 2.1.0
Use of Domains
Event structure modified
TransportCalls included as part of Transport- and Equipoment-Events
filter parameters added
pagination headers added
API-Version header added

Swaggerhub dcsa tnt 2.1.0

---

ovs/v2/ovs.yaml

IM updated to v3.2

---

ovs/v3/ovs_v3.0.0-Beta-1.yaml

Corrected the spelling error in OAS

---

bkg/notification/v1/bkg_ntf_v1.0.0-Beta-1.yaml

First suggestion to Booking Notification API

Added bkg/notification/v1/bkg_ntf_v1.0.0-Beta-1.yaml

---

models/AddressLocation.yaml
models/CityLocation.yaml
models/ErrorResponse.yaml
models/FacilityLocation.yaml
models/FacilitySMDGLocation.yaml
models/UnLocationLocation.yaml

Updated the examples.
Changed the locationType to string
Modified the Error object so it is aligned with the API Design Guide
Added the facilityLocation interface

Modify Location Interface files

---

bkg/v2/BGK_v2.0.0-Beta-1 - stoplight.yaml

Moving from SwaggerHub to StopLight.
Removing all $ref to Domains - but keeping internal $refs for now (for better comparison). Will remove internal refs in an update to Beta 2 later
@palatsangeetha you don't have to check everything as there are 4900+ lines. I am also ok with you just pressing "Approve" ;-)

Move BKG v2.0.0 Beta 1 to stoplight

---

bkg/v2/BKG_v2.0.0-Beta-2.yaml

Beta 2 is a copy of Beta 1
Used as a starting point for creating Beta 2

Create Beta 2 as a copy of Beta 1

---

ebl/v3/EBL_v3.0.0-Beta-1 - stoplight.yaml

Moving EBL 3.0.0 Beta 1 from SwaggerHub --> StopLight
Making one big yaml file with all $refs resolved

Ebl v3.0.0 Beta 1 to StopLight

---

ebl/v3/notification/EBL_NTF_v3.0.0-Beta-2.yaml

This is a copy of Beta 1 with `Beta-1` changed to `Beta-2`

EBL Notification v3.0.0 Beta 2

---

bkg/v2/BKG_v2.0.0-Beta-2.yaml

Initial setup and general modifications ([DT-982](https://dcsa.atlassian.net/browse/DT-982))
Update `importLicenseReference` and `exportLicenseReference` description ([DT-937](https://dcsa.atlassian.net/browse/DT-937))
Fix a copy paste error on the `importLicenseReference`
Change `vesselName` length from 35-->50 and `vesselIMONumber` to also allow 8 characters ([DT-948](https://dcsa.atlassian.net/browse/DT-948))
Remove the comment containing the wrong required `bookingStatus` field ([DT-848](https://dcsa.atlassian.net/browse/DT-848))
Fix wrong indention of `partyContactDetail` in examples ([DT-933](https://dcsa.atlassian.net/browse/DT-933)) - will also fix: https://github.com/dcsaorg/DCSA-OpenAPI/issues/193
Fix typos in the error object ([DT-881](https://dcsa.atlassian.net/browse/DT-881)) …

BKG v2.0.0 Beta 2

---

bkg/v2/BKG_v2.0.0-Beta-2.yaml

Removed leading spaces in example
Fixed wrong example type - should not be boolean but rather string
Add missing minItems on required arrays
Updated description of cargoGrossVolumeUnit to be a conditional field
Added missing mandatory `*` on temperatureSetpoint and temperatureUnit

Fix minor issues

---

ebl/v3/EBL_v3.0.0-Beta-2.yaml
ebl/v3/notification/EBL_NTF_v3.0.0-Beta-2.yaml

DT-917: Fix missing `s` in ShippingInstruction**s**

DT-917: Fix missing 's' in ShippingInstruction*s*

---

ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-2.yaml

Just updating the Stats API link

DT-997: Update Stats API link for Issuance

---

jit/v2/jit_v2.0.0-Beta-1.yaml

Added copy of jit-v1.2.0-Beta-2 to work on for jit_v2.0.0-Beta-1

Added jit/v2/jit_v2.0.0-Beta-1.yaml

---

ebl/v3/issuance_response/EBL_ISS_RSP_v3.0.0-Beta-2.yaml

Includes DT-992 (update Stats API link)
Expands all $ref

DT-1003: Move Issuance Response API from SwaggerHub --> StopLight

---

ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-2.yaml

DT-1002: Move Issuance API from SwaggerHub -->StopLight

---

pint/v3/EBL_PINT_v3.0.0-Beta-2.yaml

Inital move from SwaggerHub --> StopLight
resolve many $ref as it was agreed to inline SimpleTypes
Covers DT-935
Covers DT-992

DT-1032: Move PINT API from SwaggerHub --> StopLight

---

reference-data/eblsolutionproviders-v1.csv

DT-1006: Create eblsolutionproviders-v1.csv

---

ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-2.yaml

Differentiate between the `issueToParty` and the `party` objects in TD
Covers: DT-983, DT-930 and DT-984

Update IssueToParty and align PartyObjects

---

ebl/v3/surrender/EBL_SUR_v3.0.0-Beta-2.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-2.yaml

Please approve DT-1017 before this as I wrongly modified it on top
Closes: #228

DT-932: Remove BETR code from PINT API

---

ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-2.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-2.yaml

DT-1050: Set additionalProperties to false on UNLocation-Interface

DT-1050: Set additionalProperties to false on UNLocation-Interface

---

reference-data/codelistprovider-v1

Is connected to: https://dcsa.atlassian.net/browse/DT-1096

DT-1015: Add codeListProvider reference data to GitHub

---

bkg/v2/BKG_v2.0.0-Beta-1 - stoplight.yaml

Reorder properties so Beta 1 and Beta 2 are more comparable

Update Beta 1 to be comparable with Beta 2

---

bkg/v2/BKG_v2.0.0-Beta-2.yaml

@palatsangeetha somehow this was not merged into master when I published the Booking Beta 2 API - so it is **NOT** part of current master - but it **IS** part of the Booking Beta 2 API...
So this just needs to be merged in order for master to be aligned with Beta 2 (for Booking). I have checked everything - you only need to approve :-)

Fix UNLocationCode

---

ovs/v3/OVS_v3.0.1.yaml

This is a copy of OVS_3.0.0 to work for OVS_3.0.1 so renamed like that

Added ovs/v3/OVS_v3.0.1.yaml - Copy of OVS_3.0.0 to work for OVS_3.0.1

---

bkg/v2/BKG_v2.0.0-Beta-3.yaml

Fixes all descriptions messed up by StopLight

DT-1190: Fix descriptions "autocorrected" by StopLight

---

bkg/v2/notification/BKG_NTF_v3.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
ebl/v3/issuance_response/EBL_ISS_RSP_v3.0.0-Beta-3.yaml
ebl/v3/notification/EBL_NTF_v3.0.0-Beta-3.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0-Beta-3.yaml
ebl/v3/surrender_response/EBL_SUR_RSP_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

BKG Beta 3 has already been created and worked on.
This PR creates the rest (8 DT APIs) related to Booking and EBL process.
All files in this PR is a copy of Beta 2 without modifications

Created new Beta 3 versions for all DT APIs except BKG

---

cs/v1/CS_v1.0.0.yaml

Added pattern for vesselName,removed quotes by stoplight, added missing ` for RAMP

CS changes

---

an/v1/AN_v1.0.0-Beta-1.yaml
an/v1/notification/AN_NTF_v1.0.0-Beta-1.yaml
bkg/v2/BKG_v2.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

DT-1172: Remove nullable=true on stateRegion
DT-1173: Remove nullable=false on facilityCode

Fix nullable

---

bkg/v2/BKG_v2.0.0-Beta-3.yaml

`carrierSerivceCode` --> `carrierServiceCode`

DT-1181: Fix carrierSerivceCode typo

---

an/v1/AN_v1.0.0-Beta-1.yaml
an/v1/notification/AN_NTF_v1.0.0-Beta-1.yaml
bkg/v2/BKG_v2.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

Pattern was missing - now added

DT-1174: Add pattern to locationName property

---

bkg/v2/BKG_v2.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

This issue is about aligning Party objects

DT-1130: Align Party objects

---

ovs/v3/OVS_v3.0.1.yaml

Added cursor to vesselSchedules
Added location discriminator
Added additionalProperties:false to UNLocationLocation
Fixed the ErrorCodeMessage issue and added minItems to errors array.

OVS - 3.0.1 changes

---

an/v1/AN_v1.0.0-Beta-1.yaml
bkg/v2/BKG_v2.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml
reference-data/codelistprovider-EBL_v3.0.0-Beta-3.csv
reference-data/eblsolutionsproviders-EBL_v3.0.0-Beta-3.csv

* Make a Beta 3 version
* Update `eblSolutionProvider` lists
* Update `codeListProviders`
* Make sure all standards also include the 2 new SPs in the descriptions

DT-1060: Update EBL Solution Provider lists

---

an/v1/AN_v1.0.0-Beta-1.yaml
bkg/v2/BKG_v2.0.0-Beta-3.yaml
bkg/v2/notification/BKG_NTF_v3.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
ebl/v3/notification/EBL_NTF_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

All places where **Condition** is found - have been marked in bold.
Fixed a few places where it said Condition**al** --> Condition

DT-1220: Mark **Conditions** more clearly

---

bkg/v2/BKG_v2.0.0-Beta-3.yaml
ebl/v3/EBL_v3.0.0-Beta-3.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0-Beta-3.yaml
pint/v3/EBL_PINT_v3.0.0-Beta-3.yaml

Links to: https://dcsa.atlassian.net/browse/DT-1212
Modifies descriptions on `contractQuotationReference` and `serviceContractReference` (descriptions taken from IFS)

DT-1212: Modify contractQuotationReference and servieContractReference according to IFS

---

adopt/v1/ADOPT_v1.0.0.yaml
adopt/v1/README.md

Aligned with https://app.swaggerhub.com/apis/dcsaorg/DCSA_ADOPT

Create Adoption API

---

cs/v1/CS_v1.0.0.yaml

Includes description changes for the endpoints.
Added startDate, endDate for departure and arrival dates instead of range.
Moved vessel related properties to vessel Object for port schedule and vesselSchedule endpoints.
Added cutOffTimes to transportcalls in vesselschedule

Cs v1 0 0 changes

---

cs/v1/CS_v1.0.0.yaml

Added Detailed Error object
Removed the duplicate DCSA website link

Changed inline Detailed Error to object

---

ovs/v3/OVS_v3.0.1.yaml

Kept errorCodeMessage as optional as this is a patch release. Will make it mandatory in a breaking version.
Removed the x-stoplight properties.

Ovs v3.0.1 changes - Kept errorCodeMessage as optional

---

ebl/v3/EBL_v3.0.0.yaml

Includes:
[DT-1208](https://dcsa.atlassian.net/browse/DT-1208) - Reorder 'isCarriersAgentAtDestinationRequired' according to Jira comment
[DT-1208]: https://dcsa.atlassian.net/browse/DT-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Multiple fixes

---

ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

Add `MULTIMODAL` to preCarriage and onCarriage

DT-1368: Add 'MULTIMODAL' as Mode of Transport

---

ebl/v3/EBL_v3.0.0.yaml

Add the 202 (Accpeted) response to ShippingInstructions and TransportDocument endPoints.
@alanb-dscsa please review when you come back (I do believe we need to have another talk about this)
@palatsangeetha please review and add your comments or approve. Will fix any comments from Alan in a later PR
This PR is linked to [DT-1027](https://dcsa.atlassian.net/browse/DT-1027)

DT-1129: Add 202 to SI and TD

---

bkg/v2/BKG_v2.0.0.yaml

[DT-1613](https://dcsa.atlassian.net/browse/DT-1613) - Update `isoEquipmentCode` eaxmples
[DT-1613]: https://dcsa.atlassian.net/browse/DT-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1613: Update wrong value in isoEquipmentCode examples

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1483](https://dcsa.atlassian.net/browse/DT-1483) - Remove Stats API description and link
[DT-1489](https://dcsa.atlassian.net/browse/DT-1489) - Add link to API Design Guidelines
[DT-1483]: https://dcsa.atlassian.net/browse/DT-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1489]: https://dcsa.atlassian.net/browse/DT-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1489: Replace Stats API description with link to API Design Guidelines

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1214](https://dcsa.atlassian.net/browse/DT-1214) - Change all dateTime example values to be UTC instead of a dateTime using a timeZone
[DT-1214]: https://dcsa.atlassian.net/browse/DT-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1214: Change dateTime example values to be UTC instead of TimeZone

---

ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml

[DT-1515](https://dcsa.atlassian.net/browse/DT-1515) - Updating the description on the `issueTo` property
[DT-1515]: https://dcsa.atlassian.net/browse/DT-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1515: Update description of IssueTo

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1612](https://dcsa.atlassian.net/browse/DT-1612) - Add condition that all locations must point to the same place on location properties
[DT-1612]: https://dcsa.atlassian.net/browse/DT-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1612: Add condition to location objects

---

cs/v1/README.md

This PR has the changes for the issue - [APCV-1227](https://dcsa.atlassian.net/jira/software/c/projects/APCV/boards/47/backlog?selectedIssue=APCV-1227)
[APCV-1227]: https://dcsa.atlassian.net/browse/APCV-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APCV-1227- Update changelog for CS

---

cs/v1/CS_v1.0.0.yaml

Added spectral fixes
Removed quotes added by stoplight

APCV 1056 - CS spectral rule fixes

---

ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1478](https://dcsa.atlassian.net/browse/DT-1478),[DT-1477](https://dcsa.atlassian.net/browse/DT-1477) - Update definition Endorsement chain in the surrender API
[DT-1546](https://dcsa.atlassian.net/browse/DT-1546),[DT-1268](https://dcsa.atlassian.net/browse/DT-1268) - Surrender response API - Add note to surrender response
[DT-1632](https://dcsa.atlassian.net/browse/DT-1632) - Improve PINT API according to Spectral rules (add title, patterns and update property (`eBLVisualisationByCarrier` -> `eBLVisualisationByCarrierChecksum`)
[DT-1478]: https://dcsa.atlassian.net/browse/DT-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1477]: https://dcsa.atlassian.net/browse/DT-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

DT-1477,DT-1478,DT-1540,DT-1559,DT-1546: Update Surrender + PINT API

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml

[DT-1540](https://dcsa.atlassian.net/browse/DT-1540),[DT-1559](https://dcsa.atlassian.net/browse/DT-1559) - Remove everything but `202` (Accepted) as a response on `POST`, `PUT` and `PATCH`
...and fix some examples
[DT-1540]: https://dcsa.atlassian.net/browse/DT-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1559]: https://dcsa.atlassian.net/browse/DT-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1540,DT-1559: Only keep 202 Accepted as response

---

adopt/v1/ADOPT_v1.0.0_with_push.yaml

[STNG-187](https://dcsa.atlassian.net/browse/STNG-187) - Creating a new version with a `PUT` endPoint for pushing data
This PR is aligned with : https://app.swaggerhub.com/apis/dcsaorg/DCSA_ADOPT/1.0.0_with_push
[STNG-187]: https://dcsa.atlassian.net/browse/STNG-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STNG-187: Create a new version that includes `PUT`

---

ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1675](https://dcsa.atlassian.net/browse/DT-1657): Update the description for `numberOfCopiesWithCharges` and `numberOfCopiesWithoutCharges`
[DT-1675]: https://dcsa.atlassian.net/browse/DT-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1657,DT-1659: Update `numberOfCharges[With|Without]Charges` descr.

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1654](https://dcsa.atlassian.net/browse/DT-1654) - Update `errorCode` link
[DT-1654]: https://dcsa.atlassian.net/browse/DT-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1654: Update errorCode link

---

ebl/v3/EBL_v3.0.0.yaml

[DT-1750](https://dcsa.atlassian.net/browse/DT-1750) - Change `partyFunction` codes to align with issue
[DT-1750]: https://dcsa.atlassian.net/browse/DT-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1750: Update `partyFunction` codes

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[DT-1777](https://dcsa.atlassian.net/browse/DT-1777),[DT-1788](https://dcsa.atlassian.net/browse/DT-1788) - Rename `TRACE original` -> `Enigio trace:original`
[DT-1777]: https://dcsa.atlassian.net/browse/DT-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1788]: https://dcsa.atlassian.net/browse/DT-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1777: Rename "TRACE original" to "Enigio trace:original"

---

ebl/v3/issuance/EBL_ISS_v3.0.0.yaml

[DT-1807](https://dcsa.atlassian.net/browse/DT-1807): Update autogenerated 409 responseCode example in Issuance API
[DT-1807]: https://dcsa.atlassian.net/browse/DT-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1807: Modify example in Issuance 409 response

---

ebl/v3/issuance/EBL_ISS_v3.0.0.yaml

[DT-1808](https://dcsa.atlassian.net/browse/DT-1808): Add an example for ISSU request
[DT-1808]: https://dcsa.atlassian.net/browse/DT-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1808: Create ISSU example response

---

bkg/v2/BKG_v2.0.0.yaml

[DT-1802](https://dcsa.atlassian.net/browse/DT-1802?focusedCommentId=16045): Updating the description of the API to match that of the IFS
[DT-1802]: https://dcsa.atlassian.net/browse/DT-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1802: Remove the "Mandatory" part of the description

---

bkg/v2/BKG_v2.0.0.yaml

[DT-1853](https://dcsa.atlassian.net/browse/DT-1853) - Modified description of the Cancellation endPoint to emphasize it is a 202 response and as such not a cancellation
@gj0dcsa adding you as a reviewer as you have seen the mail from MSK
[DT-1853]: https://dcsa.atlassian.net/browse/DT-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1853: Modified description of the Cancellation endPoint

---

ebl/v3/EBL_v3.0.0.yaml

[DT-1752](https://dcsa.atlassian.net/browse/DT-1752),[DT-1754](https://dcsa.atlassian.net/browse/DT-1754): Add 2 additional clauses
[DT-1752]: https://dcsa.atlassian.net/browse/DT-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1754]: https://dcsa.atlassian.net/browse/DT-1754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1752,DT-1754: Add extra `requestedClauses`

---

ebl/v3/surrender/EBL_SUR_v3.0.0.yaml

[DT-1855](https://dcsa.atlassian.net/browse/DT-1855): Update tag description to make it clear who is to implement the endPoint
[DT-1855]: https://dcsa.atlassian.net/browse/DT-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DT-1855: Make it clear which party implements which endPoints

---

ebl/v3/EBL_v3.0.0.yaml

[SD14979(https://dcsa.atlassian.net/browse/SD-1497): Removing a wrongly inserted condition on `IssuingParty`

DT-1497: Remove issuingParty condition

---

tnt/v2/TNT_v2.2.0.yaml

Copying TNT 2.2.0 to GitHub. This is a 1:1 copy of what is on SwaggerHub: https://app.swaggerhub.com/apis/dcsaorg/DCSA_TNT/2.2.0

Add TNT v2.2.0 to GitHub

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[SD-513](https://dcsa.atlassian.net/browse/SD-513): Adding link to the Digital Signing document (created by Alan) located on the developer portal. Added a headline to the main API section for all EBL + Booking APIs
[SD-513]: https://dcsa.atlassian.net/browse/SD-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-513: Add link to Digital Signing document provided by Alan

---

ebl/v3/EBL_v3.0.0.yaml

As mentioned in mail :-)
@palatsangeetha fyi...

Fix wrong `identifyingCode` example

---

jit/v2/JIT_v2.0.0.yaml

Changing the structure to be a $ref insteadof `allOf`

Fix duplicate "moves"

---

jit/v2/JIT_v2.0.0.yaml

[SD-155](https://dcsa.atlassian.net/browse/SD-155),[SD-170](https://dcsa.atlassian.net/browse/SD-170): Update the API description
Sidefix - update "cycle" --> "pattern"
[SD-155]: https://dcsa.atlassian.net/browse/SD-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SD-170]: https://dcsa.atlassian.net/browse/SD-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-155,SD-170: Update the API description

---

bkg/v2/BKG_v2.0.0.yaml
dei/v1/dei_v1.0.0-Beta-1.yaml
deo/v1/deo_v1.0.0-Beta-1.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
jit/v2/JIT_v2.0.0.yaml
ovs/v3/OVS_v3.0.1.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[SD-1773](https://dcsa.atlassian.net/browse/SD-1773): Make sure we link to the http**s** version and not http
[SD-1773]: https://dcsa.atlassian.net/browse/SD-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1773: Change from http -> https

---

jit/v2/JIT_v2.0.0.yaml

[SD-1746](https://dcsa.atlassian.net/browse/SD-1746): Update `milesToDestinationPort` description
[SD-1746]: https://dcsa.atlassian.net/browse/SD-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1746: Update `milesToDestinationPort` description

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[SD-1781](https://dcsa.atlassian.net/browse/SD-1781): Clarify the `placeOfIssue` description in both EBL and BKG
[SD-1781]: https://dcsa.atlassian.net/browse/SD-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1781: Make `placeOfIssue` description more clear

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[SD-1894](https://dcsa.atlassian.net/browse/SD-1894): Downgrade referenced `API Design & Implementation Principles` from v2.**1** -> v2.**0**
[SD-1894]: https://dcsa.atlassian.net/browse/SD-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1894: Downgrade DNI principle version from 2.1 to 2.0

---

bkg/v2/BKG_v2.0.0.yaml
ebl/v3/EBL_v3.0.0.yaml
ebl/v3/issuance/EBL_ISS_v3.0.0.yaml
ebl/v3/surrender/EBL_SUR_v3.0.0.yaml
pint/v3/EBL_PINT_v3.0.0.yaml

[SD-1882](https://dcsa.atlassian.net/browse/SD-1882): Same conditions added to BKG now added to EBL, SUR, ISS and PINT
[SD-1882]: https://dcsa.atlassian.net/browse/SD-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1882: Extra conditions added

---

jit/v2/JIT_v2.0.0.yaml

[SD-1818](https://dcsa.atlassian.net/browse/SD-1818): Started to update some endPoint descriptions
[SD-1818]: https://dcsa.atlassian.net/browse/SD-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1818: Improve endpoint descriptions

---

jit/v2/README.md

Release notes for this Snapshot

Release notes for JIT Alpha as of 17 Jan 2025

---

jit/v2/README.md

[SD-612](https://dcsa.atlassian.net/browse/SD-612): Each Snapshot release should contain a list of commits connected to it
[SD-612]: https://dcsa.atlassian.net/browse/SD-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-612: Add list of commits connected to the Snapshot(s)

---

jit/v2/JIT_v2.0.0.yaml

* fix punctuation
* make sure object references are bold
* make sure property and enum value references are highlighted
* clarify that OVS is Operational Vessel Schedules

SD-2022: JIT 2.0:  Update cosmetic changes to descriptions

---

jit/v2/README.md

Update for README.md for the release next Friday - should not be merged before 14 Feb...

SD-2016: Release notes for JIT Beta as of 14 Feb 2025

---

jit/v2/JIT_v2.0.0.yaml

JIT 2.0: Update error codes in description
* Adjust line endings too

SD-2048 JIT 2.0: Update error codes in description

---

ovs/v3/OVS_v3.0.1.yaml

[SD-2224](https://dcsa.atlassian.net/browse/SD-2224): Improve `eventClassifierCode` description
___
Documentation
___
- Updated `eventClassifierCode` description with clearer definitions
- Improved explanations for Actual, Estimated, and Planned event types
- Enhanced terminology and timing details for better understanding
___
```mermaid
flowchart LR
A["Old Description"] --> B["Updated Description"]
B --> C["Actual: Real recorded time"]
B --> D["Estimated: Latest RS/CS schedule"]
B --> E["Planned: Long-term LTS schedule"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …

OVS 3.0: SD-2224: Update `eventClassifierCode` description
